import { supabase } from '../config/supabaseClient.js';

// ==================================================
// STEP 1 — AUTH CONTROLLER
// ==================================================

// POST /auth/signup - Register a new developer account
export const signup = async (req, res) => {
  try {
    const { email, password, username, fullName, bio } = req.body;

    // 1. Basic validation
    if (!email || !password || !username || !fullName) {
      return res.status(400).json({ 
        success: false, 
        message: 'Email, password, username, and full name are required' 
      });
    }

    // 2. Register user in Supabase Authentication Service
    // This creates a secure user inside Supabase's auth.users table
    const { data: authData, error: authError } = await supabase.auth.signUp({
      email,
      password
    });

    if (authError) {
      return res.status(400).json({ 
        success: false, 
        message: 'Auth registration failed', 
        error: authError.message 
      });
    }

    // Grab the unique user ID generated by Supabase
    const userId = authData.user?.id;

    if (!userId) {
      return res.status(500).json({
        success: false,
        message: 'Could not retrieve user ID from authentication provider'
      });
    }

    // 3. Create a public profile in our public.users table
    // This connects the authentication record with a profile containing custom bio/skills!
    const dbUser = {
      id: userId,
      username: username.toLowerCase().trim(),
      full_name: fullName.trim(),
      bio: bio ? bio.trim() : 'New developer at DevConnect',
      skills: [], // Defaults to empty array, user can customize on dashboard
      profile_image: fullName.split(' ').map(n => n[0]).join('').slice(0, 2).toUpperCase(), // Default SC, MO initials
      followers: 0,
      following: 0,
      posts_count: 0,
      joined_date: new Date().toLocaleDateString('en-US', { month: 'long', year: 'numeric' })
    };

    const { error: profileError } = await supabase
      .from('users')
      .insert([dbUser]);

    if (profileError) {
      console.error('Failed to create user profile:', profileError.message);
      // Optional: Delete user from auth if profile fails (for cleanup), 
      // but keeping it simple here.
    }

    res.status(201).json({
      success: true,
      message: 'User registered successfully!',
      data: {
        id: userId,
        email: authData.user.email,
        profile: dbUser
      }
    });

  } catch (error) {
    res.status(500).json({ 
      success: false, 
      message: 'Server signup error', 
      error: error.message 
    });
  }
};

// POST /auth/login - Log in an existing user
export const login = async (req, res) => {
  try {
    const { email, password } = req.body;

    if (!email || !password) {
      return res.status(400).json({ 
        success: false, 
        message: 'Email and password are required' 
      });
    }

    // 1. Authenticate with Supabase Auth
    const { data: authData, error: authError } = await supabase.auth.signInWithPassword({
      email,
      password
    });

    if (authError) {
      return res.status(401).json({ 
        success: false, 
        message: 'Invalid credentials or login failed', 
        error: authError.message 
      });
    }

    // 2. Fetch their public profile from our custom 'users' table
    const { data: profile, error: profileError } = await supabase
      .from('users')
      .select('*')
      .eq('id', authData.user.id)
      .single();

    if (profileError) {
      console.warn('Profile record not found, user might not have completed registration properly.');
    }

    // 3. Return the session token (JWT) and profile back to the frontend
    res.status(200).json({
      success: true,
      message: 'Login successful!',
      token: authData.session.access_token, // This token is sent with requests to secure routes
      user: profile || { id: authData.user.id, email: authData.user.email }
    });

  } catch (error) {
    res.status(500).json({ 
      success: false, 
      message: 'Server login error', 
      error: error.message 
    });
  }
};
